// Pinned CPU positive log1p arithmetic for original-BF16 source softplus.
// SLEEF 3.8.0 commit 5a1d179df9cf652951b59010a2d2075372d67f68,
// xlog1pf and df.h ENABLE_FMA_SP/AArch64 CONFIG=1. No Double arithmetic.
// Copyright Naoki Shibata and contributors 2010 - 2024.
// Boost Software License 1.0, reproduced below.
enum QwenOfficialSourcePositiveLog1p {
    private struct Pair {
        let high: Float
        let low: Float
    }

    // dfmul_vf2_vf2_vf
    private static func multiply(_ x: Pair, _ y: Float) -> Pair {
        let high = x.high * y
        let error = (-high).addingProduct(x.high, y)
        return Pair(high: high, low: error.addingProduct(x.low, y))
    }

    // dfadd_vf2_vf_vf
    private static func add(_ x: Float, _ y: Float) -> Pair {
        let high = x + y
        return Pair(high: high, low: (x - high) + y)
    }

    // dfadd_vf2_vf2_vf2
    private static func add(_ x: Pair, _ y: Pair) -> Pair {
        let high = x.high + y.high
        return Pair(high: high, low: (((x.high - high) + y.high) + x.low) + y.low)
    }

    // dfadd_vf2_vf2_vf
    private static func add(_ x: Pair, _ y: Float) -> Pair {
        let high = x.high + y
        return Pair(high: high, low: ((x.high - high) + y) + x.low)
    }

    // dfdiv_vf2_vf2_vf2 with ENABLE_FMA_SP.
    private static func divide(_ numerator: Pair, _ denominator: Pair) -> Pair {
        let reciprocal: Float = 1 / denominator.high
        let high = numerator.high * reciprocal
        let error = (-high).addingProduct(reciprocal, numerator.high)
        let firstCorrection = Float(1).addingProduct(-denominator.high, reciprocal)
        let correction = firstCorrection.addingProduct(-denominator.low, reciprocal)
        let numeratorCorrection = error.addingProduct(numerator.low, reciprocal)
        return Pair(high: high, low: numeratorCorrection.addingProduct(high, correction))
    }

    /// Source core log1p on its nonnegative finite domain. Softplus below its
    /// threshold20 supplies exp(x) <= exp(20), entirely inside this domain.
    static func evaluate(_ value: Float) -> Float {
        precondition(value.isFinite && value >= 0 && value <= Float(1e38))
        if value == 0 { return value }
        let plusOne = value + 1
        let scaled = plusOne * (Float(1) / Float(0.75))
        let exponent = Int32((scaled.bitPattern >> 23) & 255) - 127
        let inversePower = Float(bitPattern: UInt32(bitPattern: Int32(0x3f800000) &- (exponent << 23)))
        let mantissa = (inversePower - 1).addingProduct(value, inversePower)
        var sum = multiply(Pair(high: Float(0.69314718246459960938),
                                low: Float(-1.904654323148236017e-09)), Float(exponent))
        let quotient = divide(Pair(high: mantissa, low: 0), add(Float(2), mantissa))
        let square = quotient.high * quotient.high
        var polynomial = Float(0.3027294874)
        polynomial = Float(0.3996108174).addingProduct(polynomial, square)
        polynomial = Float(0.6666694880).addingProduct(polynomial, square)
        sum = add(sum, Pair(high: quotient.high * 2, low: quotient.low * 2))
        sum = add(sum, (square * quotient.high) * polynomial)
        return sum.high + sum.low
    }
}

// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
