import Foundation
import Testing
@testable import TurboFieldfare

@Suite struct QwenSourceRMSNormTests {
    // Generated by Qwen3_5MoeRMSNorm at transformers
    // bd15bc95a89e728bbc1224084eb3b5829428c353 and Torch 2.10.0
    // from a synthetic BF16 pattern.
    // The 32-value pattern repeats 64 times to cover all 2048 channels.
    private static let inputBF16Bits: [UInt16] = [
        0, 16270, 16011, 48697, 16455, 16479, 49175, 16435,
        16392, 49252, 16456, 15877, 49234, 15993, 16436, 48964,
        16467, 16391, 49053, 16342, 15974, 48916, 16422, 16416,
        49177, 16324, 16499, 49263, 16425, 16417, 49194, 16327,
    ]
    private static let storedWeightBF16Bits: [UInt16] = [
        48908, 49024, 15644, 48786, 48302, 16150, 16167, 48730,
        15836, 48777, 15889, 48761, 48678, 16150, 48850, 15933,
        48928, 16127, 16092, 48840, 16145, 48938, 48764, 48902,
        48537, 16100, 48847, 48940, 48659, 48872, 48925, 15863,
    ]
    private static let officialFP32Bits: [UInt32] = [
        0, 0, 1039584093, 3177328688, 1067880677, 1075263772, 3218431709, 1064368657,
        1065405514, 3213807338, 1069760826, 1026304461, 3214309773, 1042864831, 1060476811, 3200683338,
        1057445126, 1068298948, 3208639567, 1054804636, 1041894551, 3182039779, 1062603896, 1057122866,
        3211928217, 1064452505, 1064801693, 3204849961, 1064799832, 1058445179, 3202409131, 1061074068,
    ]
    // Generated by the pinned Qwen3_5MoeRMSNorm CPU fallback at Torch 2.10.0.
    // This second row uses general FP32 mantissas and its official mean differs
    // by one ULP from a Float32-squared, Double-accumulated reduction.
    private static let genericInputFP32Bits: [UInt32] = [
        1049875721, 1051175442, 1052475163, 1053774884, 1055074605, 1056374326, 1049285439, 1050585160,
        1051884881, 1053184602, 1054484323, 1055784044, 1048695157, 1049994878, 1051294599, 1052594320,
        1053894041, 1055193762, 1056493483, 1049404596, 1050704317, 1052004038, 1053303759, 1054603480,
        1055903201, 1048814314, 1050114035, 1051413756, 1052713477, 1054013198, 1055312919, 1056612640,
    ]
    private static let genericOfficialFP32Bits: [UInt32] = [
        3199214724, 0, 1065346807, 3208829856, 1066543319, 1073791190, 3214330740, 1059336260,
        1065480365, 3208575459, 1067693995, 1064095605, 3205432038, 1067189561, 1057189693, 3214109713,
        1053703140, 1071742707, 3219773540, 1054956742, 1067794166, 3198109351, 1061577050, 1057608643,
        3214007720, 1064969253, 1055736655, 3197357297, 1062680657, 1058516908, 3203051994, 1069064520,
    ]
    private static let genericOfficialMeanBits: UInt32 = 1041504371
    private static let genericDoubleMeanBits: UInt32 = 1041504372

    private func bf16(_ bits: UInt16) -> Float {
        Float(bitPattern: UInt32(bits) << 16)
    }

    private func withinFrozenTolerance(_ actual: Float, _ expected: Float) -> Bool {
        actual.isFinite && expected.isFinite &&
            abs(actual - expected) <= 1e-7 + 1e-6 * abs(expected)
    }

    @Test func fullWidthMatchesPinnedOfficialSourceAndDetectsOldReduction() throws {
        let input = Array(repeating: Self.inputBF16Bits.map(bf16), count: 64)
            .flatMap { $0 }
        let weights = Array(repeating: Self.storedWeightBF16Bits.map(bf16), count: 64)
            .flatMap { $0 }
        let expected = Array(repeating: Self.officialFP32Bits.map { Float(bitPattern: $0) },
                             count: 64).flatMap { $0 }
        #expect(input.count == 2048)
        let actual = try qwenOfficialSourceRMSNorm(input, weights)
        #expect(actual.count == expected.count)
        let failures = zip(actual, expected).filter { pair in
            !withinFrozenTolerance(pair.0, pair.1)
        }
        #expect(failures.isEmpty)

        // Negative control: this is the former sequential Float reduction.
        // The pinned fixture must reject it under the same frozen tolerance.
        let oldSquare = input.reduce(Float(0)) { $0 + $1 * $1 }
        let oldDivisor = sqrt(oldSquare / Float(input.count) + 1e-6)
        let old = zip(input, weights).map { value, weight in
            (value / oldDivisor) * (1 + weight)
        }
        let oldFailures = zip(old, expected).filter { pair in
            !withinFrozenTolerance(pair.0, pair.1)
        }
        #expect(oldFailures.count >= 512)
    }

    @Test func genericFP32RowPinsOfficialCascadeAgainstOneULPDoubleMean() throws {
        let inputPattern = Self.genericInputFP32Bits.enumerated().map { index, bits in
            let sign: UInt32 = index.isMultiple(of: 3) ? 0x8000_0000 : 0
            return Float(bitPattern: bits | sign)
        }
        let input = Array(repeating: inputPattern, count: 64).flatMap { $0 }
        let weightPattern = Self.storedWeightBF16Bits.map(bf16)
        let weights = Array(repeating: weightPattern, count: 64).flatMap { $0 }
        let expectedPattern = Self.genericOfficialFP32Bits.map { Float(bitPattern: $0) }
        let expected = Array(repeating: expectedPattern, count: 64).flatMap { $0 }

        #expect(input.count == 2048)
        #expect(expected.count == 2048)
        #expect(Self.genericOfficialMeanBits != Self.genericDoubleMeanBits)

        // Reconstruct the former wide-sum path from the exact rounded FP32
        // square terms. The result is pinned separately from the official mean.
        let squareTerms = input.map { Double($0 * $0) }
        let wideMean = Float(squareTerms.reduce(0, +) / Double(input.count))
        #expect(wideMean.bitPattern == Self.genericDoubleMeanBits)

        let actual = try qwenOfficialSourceRMSNorm(input, weights)
        #expect(actual.map(\.bitPattern) == expected.map(\.bitPattern))
    }

    @Test func rejectsInvalidShapeAndNonfiniteValues() {
        #expect(throws: QwenTextRunnerError.execution(detail: "source RMSNorm input")) {
            try qwenOfficialSourceRMSNorm([], [])
        }
        #expect(throws: QwenTextRunnerError.execution(detail: "source RMSNorm input")) {
            try qwenOfficialSourceRMSNorm([1], [0, 0])
        }
        #expect(throws: QwenTextRunnerError.execution(detail: "source RMSNorm input")) {
            try qwenOfficialSourceRMSNorm([.nan], [0])
        }
        #expect(throws: QwenTextRunnerError.execution(detail: "source RMSNorm input")) {
            try qwenOfficialSourceRMSNorm([1], [.infinity])
        }
        #expect(throws: QwenTextRunnerError.execution(detail: "source RMSNorm denominator")) {
            try qwenOfficialSourceRMSNorm([Float.greatestFiniteMagnitude], [0])
        }
        #expect(throws: QwenTextRunnerError.execution(detail: "nonfinite source RMSNorm output")) {
            try qwenOfficialSourceRMSNorm([1, 0], [Float.greatestFiniteMagnitude, 0])
        }
    }

    @Test func epsilonKeepsNearZeroInputFinite() throws {
        let output = try qwenOfficialSourceRMSNorm([1e-8, -1e-8], [0, -1])
        #expect(output.count == 2)
        #expect(output[0].isFinite)
        #expect(abs(output[0] - 1e-5) < 1e-10)
        #expect(output[1] == 0)
    }
}
