import Foundation
import Testing
@testable import TurboFieldfare
@testable import TurboFieldfareFormat

/// Independent metadata-only marker fixture. Sidecar and shard hashes are
/// literal entries from `scratch/qwen3.6-35b-a3b/official-995ad96eacd98c81ed38be0c5b274b04031597b0/SHA256SUMS`,
/// not values read from OfficialQwenSourceIdentity or generated by the production digest helper.
/// The expected digest was independently calculated with Python 3
/// `hashlib.sha256` over sorted UTF-8/LF-terminated canonical records:
/// c1ac463726b716e7db3a9fbe5db4cb690f95be7e5779aea02e49c2020bca7a7a.
@Suite(.serialized) struct OfficialSourceAdmissionTests {
    @Test func classifiesIndependentPinnedMetadataWithoutOpeningSourceRootOrShards() throws {
        let rootPath = IndependentOfficialSourceFixture.nonexistentSourceRoot
        #expect(!FileManager.default.fileExists(atPath: rootPath))
        let directory = try Self.writeDirectory(
            markerData: IndependentOfficialSourceFixture.markerData(sourceRoot: rootPath))
        defer { try? FileManager.default.removeItem(at: directory) }

        let admission = try ModelFamilyAdmission.classify(directoryURL: directory)
        guard case .qwenOfficialSource(let descriptor) = admission else {
            Issue.record("expected typed original-BF16 source admission")
            return
        }
        #expect(descriptor.kind == "official-safetensors-bf16-v1")
        #expect(descriptor.version == 1)
        #expect(descriptor.repository == IndependentOfficialSourceFixture.repository)
        #expect(descriptor.revision == IndependentOfficialSourceFixture.revision)
        #expect(descriptor.storageProfile == IndependentOfficialSourceFixture.storageProfile)
        #expect(descriptor.contentSHA256 == IndependentOfficialSourceFixture.expectedContentSHA256)
        #expect(descriptor.sourceRoot == rootPath)
    }

    @Test func classifiesMarkerAtExactMetadataCapAndRejectsOneByteOver() throws {
        let marker = try IndependentOfficialSourceFixture.markerData()
        let cap = Int(OfficialSourceDescriptor.maximumMarkerBytes)
        #expect(marker.count < cap)
        var exactlyAtCap = marker
        exactlyAtCap.append(contentsOf: repeatElement(UInt8(0x20), count: cap - marker.count))
        let accepted = try Self.writeDirectory(markerData: exactlyAtCap)
        defer { try? FileManager.default.removeItem(at: accepted) }
        guard case .qwenOfficialSource = try ModelFamilyAdmission.classify(
            directoryURL: accepted, maxManifestBytes: .max) else {
            Issue.record("source marker at its byte cap was not admitted")
            return
        }

        var oneByteOver = exactlyAtCap
        oneByteOver.append(0x20)
        let rejected = try Self.writeDirectory(markerData: oneByteOver)
        defer { try? FileManager.default.removeItem(at: rejected) }
        #expect {
            _ = try ModelFamilyAdmission.classify(
                directoryURL: rejected, maxManifestBytes: .max)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    @Test(arguments: ["versionMajor", "versionMinor", "formatMajor", "magic", "files", "tensorRegions"])
    func rejectsUnknownOrContradictoryPackedFieldsInMarker(_ field: String) throws {
        var object = IndependentOfficialSourceFixture.markerObject()
        object[field] = [:]
        let directory = try Self.writeDirectory(
            markerData: JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]))
        defer { try? FileManager.default.removeItem(at: directory) }

        #expect {
            _ = try ModelFamilyAdmission.classify(directoryURL: directory)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    @Test func rejectsChangedCanonicalDigestInMarker() throws {
        var object = IndependentOfficialSourceFixture.markerObject()
        object["contentSHA256"] = String(repeating: "0", count: 64)
        let directory = try Self.writeDirectory(
            markerData: JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]))
        defer { try? FileManager.default.removeItem(at: directory) }

        #expect {
            _ = try ModelFamilyAdmission.classify(directoryURL: directory)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    @Test func rejectsDuplicateTopLevelMembersInBothOrdersThroughStrictDecodeAndAdmission() throws {
        let escapedEquivalentRootKey = "source" + "\\" + "u0052oot"
        let duplicates = [
            "\"sourceRoot\":\"/tmp/source-a\",\"sourceRoot\":\"/tmp/source-b\"",
            "\"sourceRoot\":\"/tmp/source-b\",\"sourceRoot\":\"/tmp/source-a\"",
            "\"sourceRoot\":\"/tmp/source-a\",\"\(escapedEquivalentRootKey)\":\"/tmp/source-b\"",
            "\"\(escapedEquivalentRootKey)\":\"/tmp/source-b\",\"sourceRoot\":\"/tmp/source-a\"",
        ]
        for members in duplicates {
            try expectStrictDecodeAndAdmissionToReject(
                IndependentOfficialSourceFixture.rawMarkerData(sourceRootMembers: members))
        }
    }

    @Test func rejectsDuplicateAndEscapedEquivalentSidecarKeysInBothOrders() throws {
        let correct = try #require(IndependentOfficialSourceFixture.sidecars["config.json"])
        let altered = String(repeating: "0", count: 64)
        let escapedEquivalentName = #"config\u002ejson"#
        let duplicateMembers = [
            "\"config.json\":\"\(correct)\",\"config.json\":\"\(altered)\"",
            "\"config.json\":\"\(altered)\",\"config.json\":\"\(correct)\"",
            "\"config.json\":\"\(correct)\",\"\(escapedEquivalentName)\":\"\(correct)\"",
            "\"\(escapedEquivalentName)\":\"\(correct)\",\"config.json\":\"\(correct)\"",
        ]
        for duplicate in duplicateMembers {
            let members = IndependentOfficialSourceFixture.sidecarMembers(
                duplicateConfigurationEntries: duplicate)
            try expectStrictDecodeAndAdmissionToReject(
                IndependentOfficialSourceFixture.rawMarkerData(sidecarMapMembers: members))
        }
    }

    @Test func rejectsDuplicateShardObjectKeysAndEscapedEquivalentKeysInBothOrders() throws {
        let shard = IndependentOfficialSourceFixture.shards[0]
        let alteredName = "altered-\(shard.filename)"
        let alteredHash = String(repeating: "0", count: 64)
        let escapedEquivalentKey = #"file\u006eame"#
        let duplicateShardObjects = [
            "{\"filename\":\"\(shard.filename)\",\"filename\":\"\(alteredName)\",\"sha256\":\"\(shard.sha256)\"}",
            "{\"filename\":\"\(alteredName)\",\"filename\":\"\(shard.filename)\",\"sha256\":\"\(shard.sha256)\"}",
            "{\"filename\":\"\(shard.filename)\",\"sha256\":\"\(shard.sha256)\",\"sha256\":\"\(alteredHash)\"}",
            "{\"filename\":\"\(shard.filename)\",\"sha256\":\"\(alteredHash)\",\"sha256\":\"\(shard.sha256)\"}",
            "{\"filename\":\"\(shard.filename)\",\"\(escapedEquivalentKey)\":\"\(shard.filename)\",\"sha256\":\"\(shard.sha256)\"}",
            "{\"\(escapedEquivalentKey)\":\"\(shard.filename)\",\"filename\":\"\(shard.filename)\",\"sha256\":\"\(shard.sha256)\"}",
        ]
        for duplicateShard in duplicateShardObjects {
            try expectStrictDecodeAndAdmissionToReject(
                IndependentOfficialSourceFixture.rawMarkerData(
                    shardArrayMembers: IndependentOfficialSourceFixture.shardArray(
                        firstShardObject: duplicateShard)))
        }
    }

    @Test func rejectsGemmaV1ManifestWithOfficialSourceMarker() throws {
        let (directory, _) = try ManifestReaderTests.writeToyManifest(
            ["quant": ManifestReaderTests.quant()], config: .gemma4_26B_A4B)
        defer { try? FileManager.default.removeItem(at: directory) }
        try IndependentOfficialSourceFixture.markerData().write(
            to: directory.appendingPathComponent(OfficialSourceDescriptor.markerFilename))

        #expect {
            _ = try ModelFamilyAdmission.classify(directoryURL: directory)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    @Test func rejectsSymlinkedSourceMarkerThroughProtectedMetadataReader() throws {
        let directory = try Self.writeDirectory(markerData: nil)
        defer { try? FileManager.default.removeItem(at: directory) }
        let target = FileManager.default.temporaryDirectory
            .appendingPathComponent("official-source-marker-target-\(UUID().uuidString)")
        try IndependentOfficialSourceFixture.markerData().write(to: target)
        defer { try? FileManager.default.removeItem(at: target) }
        try FileManager.default.createSymbolicLink(
            at: directory.appendingPathComponent(OfficialSourceDescriptor.markerFilename),
            withDestinationURL: target)

        #expect {
            _ = try ModelFamilyAdmission.classify(directoryURL: directory)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    private func expectStrictDecodeAndAdmissionToReject(_ data: Data) throws {
        #expect(throws: OfficialSourceDescriptorError.self) {
            try OfficialSourceDescriptor.decodeStrict(data: data)
        }
        let directory = try Self.writeDirectory(markerData: data)
        defer { try? FileManager.default.removeItem(at: directory) }
        #expect {
            _ = try ModelFamilyAdmission.classify(directoryURL: directory)
        } throws: { error in
            guard case ModelError.indexCorrupt = error else { return false }
            return true
        }
    }

    private static func writeDirectory(markerData: Data?) throws -> URL {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("official-source-admission-\(UUID().uuidString)")
        try FileManager.default.createDirectory(
            at: directory, withIntermediateDirectories: true)
        if let markerData {
            try markerData.write(
                to: directory.appendingPathComponent(OfficialSourceDescriptor.markerFilename))
        }
        return directory
    }
}

enum IndependentOfficialSourceFixture {
    static let repository = "Qwen/Qwen3.6-35B-A3B"
    static let revision = "995ad96eacd98c81ed38be0c5b274b04031597b0"
    static let storageProfile = "original-bf16"
    static let expectedContentSHA256 =
        "c1ac463726b716e7db3a9fbe5db4cb690f95be7e5779aea02e49c2020bca7a7a"

    static let sidecars: [String: String] = [
        "config.json": "93a4693fa9d8392fbfccd4b3c9873f4bfdcb14fdede978b123d07d19675efe99",
        "configuration.json": "c1b09db419119513247e9b8b912c4b9897106c9b20c6cada7e107d993c5435eb",
        "generation_config.json": "e70c136c1b78ddc1fb0905bac8e733a4dc448d4f852a5dd75143fffc70be550e",
        "model.safetensors.index.json": "41b9356101ebf8e7519e150dc811f80c4226e727301fbb032b890f006ed0be83",
        "preprocessor_config.json": "27225450ac9c6529872ee1924fcb0962ff5634834f817040f444118116f4e516",
        "tokenizer.json": "5f9e4d4901a92b997e463c1f46055088b6cca5ca61a6522d1b9f64c4bb81cb42",
        "tokenizer_config.json": "5186f0defcd7f232382c7f0aebcd2252d073bb921ab240e407b7ae8745d2b29b",
    ]

    /// Literal filename/hash pairs transcribed from the pinned SHA256SUMS file.
    static let shards: [(filename: String, sha256: String)] = [
        ("model-00001-of-00026.safetensors", "adee7bcb930aed22e0677e58d4873b48dadb1ed8001cb5c6a0487286eadb3478"),
        ("model-00002-of-00026.safetensors", "88f2dfd2b9e73e4b70be533dbf61bcfa3c9a0003758900fcbc9d9b96f5751d4b"),
        ("model-00003-of-00026.safetensors", "8f7d72178d3f4431864978e5bcfa4c6cb1c204bc00590644d90bb19d6d522eeb"),
        ("model-00004-of-00026.safetensors", "12d7db38689ba3c8af74b23ef8523eca41e0cd95db870583d0663a3ee8a6bd60"),
        ("model-00005-of-00026.safetensors", "a836047305d0f7a7b50f0815d09d5c03ec03d59ec2c763fcdc4bf7e9936bf902"),
        ("model-00006-of-00026.safetensors", "c9080d718e9c5f9e337443225aa417d4c24d00ae7995d76ee3f1cc296b557d15"),
        ("model-00007-of-00026.safetensors", "e8c05e23131b1dd45a455ec38cfac7db14667358268623c3938d00cf3e959a68"),
        ("model-00008-of-00026.safetensors", "4b6a6d495053089f4a80e7cbc82e848fba44e2c0c60122233d8fdff79fa7b296"),
        ("model-00009-of-00026.safetensors", "a31a954bb72d1c714e751bf0aabf2ff533f5a509693ebf7dd22ad6e90be46f67"),
        ("model-00010-of-00026.safetensors", "246560e66570fe746653b8443e245dc334c9b8b831ea43d2d9f1b7d98623994e"),
        ("model-00011-of-00026.safetensors", "7180392817fe3ecb3a27a1da43b7ff22c1a94806bac49975f9f122c3126df675"),
        ("model-00012-of-00026.safetensors", "043fb525f6625c2f2acb75e65a9959ee3fa7b6e3fdd2034b5cfe1859b01d3cfb"),
        ("model-00013-of-00026.safetensors", "33a20fb20a21379bf43c84a43105f9c0cc35bd50d740b1c302dcbe4b700f5425"),
        ("model-00014-of-00026.safetensors", "be823e33c5cb6120ad3769d081f34a2449dc2358041fca7c29d636c1ba19130d"),
        ("model-00015-of-00026.safetensors", "a89d547c6f9d0b535ee5ea2f2478f163089539f3f0dd330cb23d278a19d76123"),
        ("model-00016-of-00026.safetensors", "69fc3ae0316482288afdcdd0b9eb7d626703ae26f7567e89aa3fc8d1ffd4ff5b"),
        ("model-00017-of-00026.safetensors", "e356e3943cf3852b76bb8992e674f3256013e27d54b78e8250514151cdc29637"),
        ("model-00018-of-00026.safetensors", "9e5e63fd1cc7d6848330c1fa363dfcb661bbc2ac87e672d0e28b71c9cb7f3c7f"),
        ("model-00019-of-00026.safetensors", "708644ad34f1de727bf484f396944d8ec628645d52c183e9a992e65671685e21"),
        ("model-00020-of-00026.safetensors", "ca083a1d1aa64f8e8a785998f543a43374f13436dc85d396eee4e72c7a84e1ae"),
        ("model-00021-of-00026.safetensors", "ada4ae48f3d48fe01b4c53f2f82bce25e798a9631fd33959c881156fef2ccbce"),
        ("model-00022-of-00026.safetensors", "def207fb42d7db31efb512755557763c23233c6e4d4c433027cb5102a7bce2f7"),
        ("model-00023-of-00026.safetensors", "864d52ca7768a36f514069222e8de8626264ae124097ba8fcce5b5da2c6e2ed7"),
        ("model-00024-of-00026.safetensors", "391acd27420cdce5935ff18152423c70620d19dac3c39a5ef1a81d369f82d737"),
        ("model-00025-of-00026.safetensors", "778e7f76602f05042b69ba7f3ec91f1fdffef390540b16074041c258fb81d154"),
        ("model-00026-of-00026.safetensors", "1a97404220077ed3d4182e10385b152004cab608377f50cec9f54a6b8d28b613"),
    ]

    static var nonexistentSourceRoot: String {
        "/tmp/official-source-root-not-created-\(UUID().uuidString)"
    }

    static func markerObject(sourceRoot: String = nonexistentSourceRoot) -> [String: Any] {
        [
            "kind": "official-safetensors-bf16-v1",
            "version": 1,
            "repository": repository,
            "revision": revision,
            "storageProfile": storageProfile,
            "sidecarSHA256": sidecars,
            "shards": shards.map { ["filename": $0.filename, "sha256": $0.sha256] },
            "sourceRoot": sourceRoot,
            "contentSHA256": expectedContentSHA256,
        ]
    }

    static func markerData(sourceRoot: String = nonexistentSourceRoot) throws -> Data {
        try JSONSerialization.data(
            withJSONObject: markerObject(sourceRoot: sourceRoot), options: [.sortedKeys])
    }

    static func rawMarkerData(
        sidecarMapMembers: String? = nil,
        shardArrayMembers: String? = nil,
        sourceRootMembers: String? = nil
    ) -> Data {
        let sidecarsJSON = sidecarMapMembers ?? sidecars.keys.sorted().map { name in
            "\"\(name)\":\"\(sidecars[name]!)\""
        }.joined(separator: ",")
        let shardsJSON = shardArrayMembers ?? shardArray()
        let rootJSON = sourceRootMembers
            ?? "\"sourceRoot\":\"\(nonexistentSourceRoot)\""
        let json = """
        {"kind":"official-safetensors-bf16-v1","version":1,
        "repository":"\(repository)","revision":"\(revision)",
        "storageProfile":"\(storageProfile)",
        "sidecarSHA256":{\(sidecarsJSON)},"shards":[\(shardsJSON)],
        \(rootJSON),"contentSHA256":"\(expectedContentSHA256)"}
        """
        return Data(json.utf8)
    }

    static func sidecarMembers(duplicateConfigurationEntries: String) -> String {
        let otherEntries = sidecars.keys.filter { $0 != "config.json" }.sorted().map { name in
            "\"\(name)\":\"\(sidecars[name]!)\""
        }
        return ([duplicateConfigurationEntries] + otherEntries).joined(separator: ",")
    }

    static func shardArray(firstShardObject: String? = nil) -> String {
        let first: String
        if let firstShardObject {
            first = firstShardObject
        } else {
            let shard = shards[0]
            first = "{\"filename\":\"\(shard.filename)\",\"sha256\":\"\(shard.sha256)\"}"
        }
        let rest = shards.dropFirst().map {
            "{\"filename\":\"\($0.filename)\",\"sha256\":\"\($0.sha256)\"}"
        }
        return ([first] + rest).joined(separator: ",")
    }
}
