#ifndef QWEN_PINNED_SOURCE_EXP
#define QWEN_PINNED_SOURCE_EXP
#include <metal_stdlib>
using namespace metal;

// SLEEF 3.8.0 xexpf, AArch64 CONFIG=1 explicit FMA operations, commit
// 5a1d179df9cf652951b59010a2d2075372d67f68. Scratch GPU qualification helper.
// Copyright Naoki Shibata and contributors 2010 - 2024.
// Boost Software License 1.0, reproduced below.
inline float qwenSourceExpReduced(float value, thread int& exponent) {
#pragma clang fp contract(off)
    exponent = int(rint(value * 1.442695040888963407359924681001892137426645954152985934135449406931f));
    const float quotient = float(exponent);
    float reduced = fma(quotient, -0.693145751953125f, value);
    reduced = fma(quotient, -1.428606765330187045e-06f, reduced);
    float polynomial = 0.000198527617612853646278381f;
    polynomial = fma(polynomial, reduced, 0.00139304355252534151077271f);
    polynomial = fma(polynomial, reduced, 0.00833336077630519866943359f);
    polynomial = fma(polynomial, reduced, 0.0416664853692054748535156f);
    polynomial = fma(polynomial, reduced, 0.166666671633720397949219f);
    polynomial = fma(polynomial, reduced, 0.5f);
    const float square = reduced * reduced;
    return 1.0f + fma(square, polynomial, reduced);
}

inline float qwenSourceExpFloatDirect(float value) {
#pragma clang fp contract(off)
    if (value < -104.0f) return 0.0f;
    if (value > 100.0f) return INFINITY;
    if (isnan(value)) return value + value;
    int exponent;
    float polynomial = qwenSourceExpReduced(value, exponent);
    const int halfExponent = exponent >> 1;
    const float firstScale = as_type<float>(uint(halfExponent + 127) << 23);
    const float secondScale = as_type<float>(uint(exponent - halfExponent + 127) << 23);
    return (polynomial * firstScale) * secondScale;
}

// Exact power-of-two multiplication for a positive normal input. For a
// subnormal result, round the shifted mantissa to nearest even in integer bits.
// This implements the source's final multiplication when GPU math flushes
// subnormal arithmetic results. No general floating-point emulation is used.
inline float qwenSourceExpScale(float normal, int exponent) {
    const uint bits = as_type<uint>(normal);
    const int resultExponent = int((bits >> 23) & 255u) + exponent;
    if (resultExponent >= 255) return INFINITY;
    if (resultExponent > 0) {
        return as_type<float>((bits & 0x007fffffu) | (uint(resultExponent) << 23));
    }
    const uint shift = uint(1 - resultExponent);
    if (shift > 24u) return 0.0f;
    const uint significand = (bits & 0x007fffffu) | 0x00800000u;
    uint rounded = significand >> shift;
    const uint remainder = significand & ((1u << shift) - 1u);
    const uint midpoint = 1u << (shift - 1u);
    if (remainder > midpoint || (remainder == midpoint && (rounded & 1u))) ++rounded;
    return as_type<float>(rounded);
}

inline float qwenSourceExpFloatBitScale(float value) {
#pragma clang fp contract(off)
    if (value < -104.0f) return 0.0f;
    if (value > 100.0f) return INFINITY;
    if (isnan(value)) return value + value;
    int exponent;
    const float polynomial = qwenSourceExpReduced(value, exponent);
    const int halfExponent = exponent >> 1;
    const float firstScale = as_type<float>(uint(halfExponent + 127) << 23);
    return qwenSourceExpScale(polynomial * firstScale, exponent - halfExponent);
}

// Boost Software License - Version 1.0 - August 17th, 2003
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#endif
